Update `bolt.Open` call with options parameter
It is currently not possible to `go get` the package
because of backwards incompatible `github.com/boltdb/bolt`
API changes.

~~~bash
$ go get github.com/boltdb/boltd/...
../../boltdb/boltd/cmd/boltd/main.go:27: not enough arguments in call to bolt.Open
~~~