Fix main.go - bolt.Open missing third argument.
This fixes the error:

# github.com/boltdb/boltd/cmd/boltd
c:\...\Gocode\src\github.com\boltdb\boltd\cmd\boltd\main.go:27: not enough arguments in call to bolt.Open